// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/bloodmoney2-blog" | "/blog/farm-merge-harvest-blog" | "/blog/lovemoney-blog" | "/blog/normal-maths-blog" | "/blog/ormblok-blog" | "/blog/poor-bunny-blog" | "/blog/roly-pony-blog" | "/blog/scarlet-shift-blog" | "/blog/soflo-wheelie-life-blog" | "/blog/sprunki-looping-the-rooms-blog" | "/blog/super-willie-world-2-blog" | "/blood-money-2" | "/epstein-clicker" | "/farm-merge-harvest" | "/games" | "/kingdom-of-marionettes" | "/lovemoney" | "/normal-maths" | "/ormblok" | "/poor-bunny" | "/privacy-policy" | "/roly-pony" | "/scarlet-shift" | "/soflo-wheelie-life" | "/sprunki-looping-the-rooms" | "/sprunki-phase-10" | "/super-willie-world-2" | "/terms-of-service" | "/zombie-merge"
type PageRoutes = never
type LayoutRoutes = "/" | "/blog" | "/blog/bloodmoney2-blog" | "/blog/lovemoney-blog" | "/blog/normal-maths-blog" | "/blog/ormblok-blog" | "/blog/poor-bunny-blog" | "/blog/roly-pony-blog" | "/blog/scarlet-shift-blog" | "/blog/soflo-wheelie-life-blog" | "/blog/sprunki-looping-the-rooms-blog" | "/blog/super-willie-world-2-blog" | "/blood-money-2" | "/epstein-clicker" | "/farm-merge-harvest" | "/games" | "/kingdom-of-marionettes" | "/lovemoney" | "/normal-maths" | "/ormblok" | "/poor-bunny" | "/privacy-policy" | "/roly-pony" | "/scarlet-shift" | "/soflo-wheelie-life" | "/sprunki-looping-the-rooms" | "/super-willie-world-2" | "/terms-of-service" | "/zombie-merge"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/blog": {}
  "/blog/bloodmoney2-blog": {}
  "/blog/farm-merge-harvest-blog": {}
  "/blog/lovemoney-blog": {}
  "/blog/normal-maths-blog": {}
  "/blog/ormblok-blog": {}
  "/blog/poor-bunny-blog": {}
  "/blog/roly-pony-blog": {}
  "/blog/scarlet-shift-blog": {}
  "/blog/soflo-wheelie-life-blog": {}
  "/blog/sprunki-looping-the-rooms-blog": {}
  "/blog/super-willie-world-2-blog": {}
  "/blood-money-2": {}
  "/epstein-clicker": {}
  "/farm-merge-harvest": {}
  "/games": {}
  "/kingdom-of-marionettes": {}
  "/lovemoney": {}
  "/normal-maths": {}
  "/ormblok": {}
  "/poor-bunny": {}
  "/privacy-policy": {}
  "/roly-pony": {}
  "/scarlet-shift": {}
  "/soflo-wheelie-life": {}
  "/sprunki-looping-the-rooms": {}
  "/sprunki-phase-10": {}
  "/super-willie-world-2": {}
  "/terms-of-service": {}
  "/zombie-merge": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blog": never
  "/blog/bloodmoney2-blog": never
  "/blog/lovemoney-blog": never
  "/blog/normal-maths-blog": never
  "/blog/ormblok-blog": never
  "/blog/poor-bunny-blog": never
  "/blog/roly-pony-blog": never
  "/blog/scarlet-shift-blog": never
  "/blog/soflo-wheelie-life-blog": never
  "/blog/sprunki-looping-the-rooms-blog": never
  "/blog/super-willie-world-2-blog": never
  "/blood-money-2": never
  "/epstein-clicker": never
  "/farm-merge-harvest": never
  "/games": never
  "/kingdom-of-marionettes": never
  "/lovemoney": never
  "/normal-maths": never
  "/ormblok": never
  "/poor-bunny": never
  "/privacy-policy": never
  "/roly-pony": never
  "/scarlet-shift": never
  "/soflo-wheelie-life": never
  "/sprunki-looping-the-rooms": never
  "/super-willie-world-2": never
  "/terms-of-service": never
  "/zombie-merge": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
