// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/blog/bloodmoney2-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/bloodmoney2-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/bloodmoney2-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/farm-merge-harvest-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/farm-merge-harvest-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/farm-merge-harvest-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/lovemoney-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/lovemoney-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/lovemoney-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/normal-maths-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/normal-maths-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/normal-maths-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/ormblok-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/ormblok-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/ormblok-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/poor-bunny-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/poor-bunny-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/poor-bunny-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/roly-pony-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/roly-pony-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/roly-pony-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/scarlet-shift-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/scarlet-shift-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/scarlet-shift-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/soflo-wheelie-life-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/soflo-wheelie-life-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/soflo-wheelie-life-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/super-willie-world-2-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/super-willie-world-2-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/super-willie-world-2-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blood-money-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blood-money-2">> = Specific
  const handler = {} as typeof import("../../src/app/blood-money-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/epstein-clicker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/epstein-clicker">> = Specific
  const handler = {} as typeof import("../../src/app/epstein-clicker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/farm-merge-harvest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/farm-merge-harvest">> = Specific
  const handler = {} as typeof import("../../src/app/farm-merge-harvest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games">> = Specific
  const handler = {} as typeof import("../../src/app/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kingdom-of-marionettes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kingdom-of-marionettes">> = Specific
  const handler = {} as typeof import("../../src/app/kingdom-of-marionettes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lovemoney/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lovemoney">> = Specific
  const handler = {} as typeof import("../../src/app/lovemoney/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/normal-maths/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/normal-maths">> = Specific
  const handler = {} as typeof import("../../src/app/normal-maths/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ormblok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ormblok">> = Specific
  const handler = {} as typeof import("../../src/app/ormblok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/poor-bunny/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/poor-bunny">> = Specific
  const handler = {} as typeof import("../../src/app/poor-bunny/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/roly-pony/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roly-pony">> = Specific
  const handler = {} as typeof import("../../src/app/roly-pony/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scarlet-shift/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scarlet-shift">> = Specific
  const handler = {} as typeof import("../../src/app/scarlet-shift/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/soflo-wheelie-life/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/soflo-wheelie-life">> = Specific
  const handler = {} as typeof import("../../src/app/soflo-wheelie-life/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sprunki-phase-10/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sprunki-phase-10">> = Specific
  const handler = {} as typeof import("../../src/app/sprunki-phase-10/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-willie-world-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-willie-world-2">> = Specific
  const handler = {} as typeof import("../../src/app/super-willie-world-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/zombie-merge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/zombie-merge">> = Specific
  const handler = {} as typeof import("../../src/app/zombie-merge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/blog/bloodmoney2-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/bloodmoney2-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/bloodmoney2-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/lovemoney-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/lovemoney-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/lovemoney-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/normal-maths-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/normal-maths-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/normal-maths-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/ormblok-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/ormblok-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/ormblok-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/poor-bunny-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/poor-bunny-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/poor-bunny-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/roly-pony-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/roly-pony-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/roly-pony-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/scarlet-shift-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/scarlet-shift-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/scarlet-shift-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/soflo-wheelie-life-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/soflo-wheelie-life-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/soflo-wheelie-life-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/super-willie-world-2-blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/super-willie-world-2-blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/super-willie-world-2-blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blood-money-2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blood-money-2">> = Specific
  const handler = {} as typeof import("../../src/app/blood-money-2/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/epstein-clicker/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/epstein-clicker">> = Specific
  const handler = {} as typeof import("../../src/app/epstein-clicker/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/farm-merge-harvest/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/farm-merge-harvest">> = Specific
  const handler = {} as typeof import("../../src/app/farm-merge-harvest/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/games/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/games">> = Specific
  const handler = {} as typeof import("../../src/app/games/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kingdom-of-marionettes/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/kingdom-of-marionettes">> = Specific
  const handler = {} as typeof import("../../src/app/kingdom-of-marionettes/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lovemoney/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lovemoney">> = Specific
  const handler = {} as typeof import("../../src/app/lovemoney/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/normal-maths/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/normal-maths">> = Specific
  const handler = {} as typeof import("../../src/app/normal-maths/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ormblok/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ormblok">> = Specific
  const handler = {} as typeof import("../../src/app/ormblok/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/poor-bunny/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/poor-bunny">> = Specific
  const handler = {} as typeof import("../../src/app/poor-bunny/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/roly-pony/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/roly-pony">> = Specific
  const handler = {} as typeof import("../../src/app/roly-pony/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scarlet-shift/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/scarlet-shift">> = Specific
  const handler = {} as typeof import("../../src/app/scarlet-shift/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/soflo-wheelie-life/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/soflo-wheelie-life">> = Specific
  const handler = {} as typeof import("../../src/app/soflo-wheelie-life/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-willie-world-2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-willie-world-2">> = Specific
  const handler = {} as typeof import("../../src/app/super-willie-world-2/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms-of-service/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../src/app/terms-of-service/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/zombie-merge/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/zombie-merge">> = Specific
  const handler = {} as typeof import("../../src/app/zombie-merge/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
